
renderer_module: 'lib.networks.renderer.tpose_renderer'
trainer_module: 'lib.train.trainers.tpose_trainer'


visualizer_module: 'lib.visualizers.if_nerf'
visualizer_path: 'lib/visualizers/if_nerf.py'


train:
    batch_size: 1
    collator: ''
    lr: 5e-4
    weight_decay: 0
    epoch: 400
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 1000
    num_workers: 16

test:
    sampler: 'FrameSampler'
    batch_size: 1
    collator: ''
debug:
    train_mesh: False

ep_iter: 500
save_ep: 200
eval_ep: 1000

# training options
train_th: 0.1
norm_th: 0.1

# rendering options
i_embed: 0
xyz_res: 10
view_res: 4
raw_noise_std: 0

N_samples: 64
N_importance: 128
N_rand: 1024

perturb: 1
white_bkgd: False

render_views: 50

# data options
# H: 1002
# W: 1000
ratio: 1.
training_view: [0, 1, 2]
init_sdf: 'bigpose_3d_s9p'
num_latent_code: 260
num_train_frame: 260
num_eval_frame: 133
begin_ith_frame: 0
frame_interval: 5
smpl: 'new_smpl'
vertices: 'new_vertices'
params: 'new_params'
big_box: True

voxel_size: [0.005, 0.005, 0.005]  # dhw

# record options
log_interval: 1


train_init_sdf_cfg:

    test:
        sampler: ''

    init_sdf: 'no_pretrain'

forward_rendering_single_cfg:
    train_dataset_module: 'lib.datasets.totalselfscan.tpose_fwrender_bfh_multi_dataset'
    test_dataset_module: 'lib.datasets.totalselfscan.tpose_fwrender_bfh_multi_dataset'

    renderer_module: 'lib.networks.renderer.tpose_forward_renderer'
    trainer_module: 'lib.train.trainers.tpose_forward_trainer'

    N_samples: 5
    z_interval: 0.04
    select_view: False
    process:
        smooth_rgb: True
    test:
        frame_sampler_interval: 10

    novel_pose_cfg:
        test_dataset_module: 'lib.datasets.totalselfscan.tpose_fwrender_bfh_multi_novel_pose_dataset'
        renderer_module: 'lib.networks.renderer.tpose_forward_renderer'
        trainer_module: 'lib.train.trainers.tpose_forward_trainer'
        visualizer_module: 'lib.visualizers.if_nerf_novel_pose'

        select_view: False

        test:
            frame_sampler_interval: 3
            sampler: 'FrameSampler'

    novel_view_cfg:
        test_dataset_module: 'lib.datasets.totalselfscan.tpose_fwrender_bfh_multi_novel_view_dataset'
        renderer_module: 'lib.networks.renderer.tpose_forward_renderer'
        trainer_module: 'lib.train.trainers.tpose_forward_trainer'
        visualizer_module: 'lib.visualizers.if_nerf_novel_view'

        select_view: True



mesh_cfg:

    renderer_module: 'lib.networks.renderer.sdf_mesh_renderer'
    evaluator_module: 'lib.evaluators.mesh_evaluator'
    visualizer_module: 'lib.visualizers.t0_mesh'

    mesh_th: 0.

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 10

mesh_train_cfg:
    train_dataset_module: 'lib.datasets.totalselfscan.posed_frame_mesh_dataset_total'
    test_dataset_module: 'lib.datasets.totalselfscan.posed_frame_mesh_dataset_total'
    network_module: 'lib.networks.totalselfscan.anisdf_bfh_multi_network_nointer_trick_rgb_base_total_union'
    renderer_module: 'lib.networks.renderer.sdf_posed_mesh_renderer'
    evaluator_module: 'lib.evaluators.mesh_evaluator'
    visualizer_module: 'lib.visualizers.t0_mesh'

    mesh_th: 0.

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 10

mesh_single_part_cfg:
    train_dataset_module: 'lib.datasets.totalselfscan.tpose_frame_mesh_dataset_total'
    test_dataset_module: 'lib.datasets.totalselfscan.tpose_frame_mesh_dataset_total'
    renderer_module: 'lib.networks.renderer.sdf_mesh_renderer'
    evaluator_module: 'lib.evaluators.mesh_evaluator'
    visualizer_module: 'lib.visualizers.t0_mesh'

    mesh_th: 0.

    test:
        sampler: 'FrameSampler'
        frame_sampler_interval: 10

